### ISSUE TITLE
Trivial python 3 incompatabilities

### ISSUE THREAD

**Issue by prhbrt** [eborboihuc/SoundNet-tensorflow#1]
I think it would be a good idea to use python 3 syntax regarding print-statements, it's a minor thing that will probably allow this to be python 3 compatible.

**Comment by eborboihuc** [comment]
Thanks for opening this issue. I believe that it is a good move.
[They](https://github.com/eborboihuc/SoundNet-tensorflow/commit/ccbff2e238a1fea7e8ae8e7d482b4ed371c1be2a) are now Python 3 compatible. Please tell me if there is any bug since I only test on my machine.

**Comment by prhbrt** [comment]
Thanks for your efforts!
